FROM node:stretch
#FROM node:alpine

RUN apt-get update && apt-get install -y \
  supervisor \
  apache2 \
  tzdata \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

ENV TZ=America/Argentina/Buenos_Aires
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN a2enmod rewrite
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

COPY docker/supervisor/apache.conf /etc/supervisor/conf.d
COPY docker/apache/000-default.conf /etc/apache2/sites-available
COPY docker/entrypoint.sh /

RUN curl -o- -L https://yarnpkg.com/install.sh | bash
RUN yarn global add @angular/cli
RUN ng set --global packageManager=yarn

COPY src /src
WORKDIR /src

RUN cd /src/login-ui && yarn install
RUN cd /src/login-ui && ng build --configuration=econo --build-optimizer --aot --i18n-file src/messages.xlf --i18n-format xlf --i18n-locale es
#RUN cd /src/login-ui && ng build --prod --build-optimizer --aot
EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]
#ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf",  "--nodaemon"]
