version: "3.5"
services:
  db_hydra:
    image: postgres
    ports:
      - 5432:5432/tcp
    volumes:
      - data-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hydra
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: 5b4eefc
    network_mode: "host"

  hydra:
    image: oryd/hydra:v1.5
    depends_on:
      - "db_hydra"
    ports:
      - 4444:4444/tcp
      - 4445:4445/tcp
    command:
      serve all --dangerous-force-http
    environment:
      SYSTEM_SECRET: 1210926c4d161111111111111111111111111
      DATABASE_URL: postgres://hydra:5b4eefc@192.168.10.3:5432/hydra?sslmode=disable
      OAUTH2_ISSUER_URL: http://oidc:4444
      urls.self.issuer: http://oidc:4444
      OAUTH2_LOGIN_URL: http://localhost:1005/login/
      OAUTH2_CONSENT_URL: http://localhost:1005/consent/
      OAUTH2_CONSENT_PROVIDER: http://localhost:1005/consent/
      OAUTH2_ERROR_URL: http://localhost:1005/oauth_error
      LOGOUT_REDIRECT_URL: http://localhost:1005
      OAUTH2_LOGOUT_REDIRECT_URL: http://localhost:1005
      HTTPS_ALLOW_TERMINATION_FROM: 0.0.0.0/0
      key serve.tls.allow_termination_from: 0.0.0.0/0
      ADMIN_PORT: 4445
      ADMIN_HOST: 0.0.0.0
      PUBLIC_PORT: 4444
      PUBLIC_HOST: 0.0.0.0
      serve.public.host: 0.0.0.0
      serve.public.port: 4444
      LOG_LEVEL:  debug
    network_mode: "host"

volumes:
  data-volume:
